version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - build
image: Visual Studio 2019
build_script:
- cmd: >-
    nuget source Add -Name "foxbot Discord addons" -Source https://www.myget.org/F/foxbot-discord-addons/api/v3/index.json

    dotnet build -c Release -f net461
artifacts:
- path: '**\bin\Release\hpenney2clone.exe'
