version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "hpenney3.csproj" }}
      - run:
          name: "Add foxbot Discord addons source"
          command: nuget source Add -Name "foxbot Discord addons" -Source https://www.myget.org/F/foxbot-discord-addons/api/v3/index.json
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "hpenney3.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -f net461
#      - run:
#          name: "Test the executable"
#          command: .\bin\Release\netcoreapp2.1\win10-x64\publish\circleci-demo-windows.exe
      - store_artifacts:
          path: .\bin\Release\net461\hpenney2clone.exe